services:
  christmas-site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:80"
      - "5006:443"
    volumes:
      - ./:/usr/share/nginx/html
    restart: unless-stopped
