services:
  birthday-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: birthday_site
    volumes:
      - ./:/usr/share/nginx/html
    restart: unless-stopped
    ports:
      - "8080:8080"

networks:
  nginx-network:
    external: true
