services:
  flower-site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80"
      - "1235:443"
    volumes:
      - ./:/usr/share/nginx/html
    restart: unless-stopped
